### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by joyce677** [chazzjimel/newgpt_turbo#3]
[ERROR][2023-07-05 06:59:39][chat_channel.py:291] - Worker return exception: Error communicating with OpenAI: Invalid URL 'None/chat/completions': No scheme supplied. Perhaps you meant https://none/chat/completions?
﻿Traceback (most recent call last):

已经用的最新的：openai.api_base = conf().get("open_ai_api_base","https://api.openai.com/v1")

还是会报错

**Comment by cheungchazz** [comment]
"open_ai_api_base": "https://api.openai.com/v1"

检查主项目config.json是否有以上键值对，把值发上来

**Comment by joyce677** [comment]
> "open_ai_api_base": " https://api.openai.com/v1 "
> 
> 检查主项目config.json是否有以上键值对，把值发上来

问题解决，能够正常调用Newgpt了。
但有时候感觉回复的延迟高或者遇到提问一些问题会报错：

[ERROR][2023-07-05 08:35:29][chat_channel.py:291] - Worker return exception: The server is overloaded or not ready yet.
﻿Traceback (most recent call last):
﻿File "/nix/store/al6g1zbk8li6p8mcyp0h60d08jaahf8c-python3-3.10.9/lib/python3.10/concurrent/futures/thread.py", line 58, in run
﻿result = self.fn(*self.args, **self.kwargs)
﻿File "/app/channel/chat_channel.py", line 149, in _handle
﻿reply = self._generate_reply(context)
﻿File "/app/channel/chat_channel.py", line 161, in _generate_reply
﻿e_context = PluginManager().emit_event(
﻿File "/app/plugins/plugin_manager.py", line 165, in emit_event
﻿instance.handlers[e_context.event](e_context, *args, **kwargs)
﻿File "/app/plugins/newgpt_turbo/main.py", line 93, in on_handle_context
﻿conversation_output = self.run_conversation(input_messages, e_context)
﻿File "/app/plugins/newgpt_turbo/main.py", line 111, in run_conversation
﻿response = openai.ChatCompletion.create(
﻿File "/opt/venv/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
﻿return super().create(*args, **kwargs)
﻿File "/opt/venv/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
﻿response, _, api_key = requestor.request(
﻿File "/opt/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 226, in request
﻿resp, got_stream = self._interpret_response(result, stream)
﻿File "/opt/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 619, in _interpret_response
﻿self._interpret_response_line(
﻿File "/opt/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 662, in _interpret_response_line
﻿raise error.ServiceUnavailableError(
﻿openai.error.ServiceUnavailableError: The server is overloaded or not ready yet.

**Comment by cheungchazz** [comment]
OpenAI服务器的问题，看账号是否限速

**Comment by joyce677** [comment]
> OpenAI服务器的问题，看账号是否限速


刚发现搜索功能没办法正常使用，随便搜什么都提示这个，已配置bing key 。

[AI]很抱歉，当前无法获取到关于xxxxxxxx的有效信息内容。请您尝试更换关键词或稍后再次尝试。如果有其他问题，我会尽力帮助您解答。谢谢！

**Comment by cheungchazz** [comment]
> > OpenAI服务器的问题，看账号是否限速
> 
> 
> 刚发现搜索功能没办法正常使用，随便搜什么都提示这个，已配置bing key 。
> 
> [AI]很抱歉，当前无法获取到关于xxxxxxxx的有效信息内容。请您尝试更换关键词或稍后再次尝试。如果有其他问题，我会尽力帮助您解答。谢谢！
> 
检查日志，看是不是谷歌搜索配置问题，可以用必应关键词试试先，比如必应搜索***

**Comment by joyce677** [comment]
> 

 感谢，原来默认调用的是谷歌搜索。谷歌没配置，所以搜索不了，用Bing搜的话必须要加Bing的前缀。

**Comment by cheungchazz** [comment]
> > 
> 
> 感谢，原来默认调用的是谷歌搜索。谷歌没配置，所以搜索不了，用Bing搜的话必须要加Bing的前缀。

是的，默认调用谷歌，谷歌搜索普通的好用点，bing搜新闻好

**Comment by joyce677** [comment]
> 

大佬，主项目有个定时的插件，那个插件还是用$tool 做为前缀调用，跟newgpt不适配，。我感觉那个定时的加你的项目应该会很好用，定时搜索相关的东西，定时给你发天气预报等等..

**Comment by cheungchazz** [comment]
> > 
> 
> 大佬，主项目有个定时的插件，那个插件还是用$tool 做为前缀调用，跟newgpt不适配，。我感觉那个定时的加你的项目应该会很好用，定时搜索相关的东西，定时给你发天气预报等等..

不晓得，我这插件随便写的，定时插件优先级高，然后传递关键词就行了，但是itchat没有唯一ID识别，项目一旦重启就很难了
