### ISSUE TITLE
google search 经常读取不到网页内容

### ISSUE THREAD

**Issue by uni345** [chazzjimel/newgpt_turbo#4]
search_google.py:92

链接内容低于200个字符：https://www.mizunousa.com/search-results?w=%E6%AD%A6%E6%B1%89%E4%BB%A3%E5%BC%80%E5%8F%91%E7%A5%A8-%E6%AD%A6%E6%B1%89%E4%BB%A3%E5%BC%80%E5%8F%91%E7%A5%A8%E2%94%83%E5%8A%A0%E5%BE%AE%E4%BF%A1:%20hnx618618%E2%94%83%E4%BF%9D%E7%9C%9F(YA)%E5%8F%AF%E9%9D%A0%E2%94%83%E4%BD%8F%E5%AE%BF%E5%8F%91%E7%A5%A8-%E9%85%92%E5%BA%97%E5%8F%91%E7%A5%A8-%E9%A4%90%E8%B4%B9%E5%8F%91%E7%A5%A8-%E9%A4%90%E9%A5%AE%E5%8F%91%E7%A5%A8-%E5%B9%BF%E5%91%8A-%E5%92%A8%E8%AF%A2-%E6%9D%90%E6%96%99-%E8%8D%AF%E5%93%81-%E4%BA%94%E9%87%91-%E7%A7%9F%E8%BD%A6-%E5%8A%9E%E5%85%AC%E7%94%A8%E5%93%81%E7%AD%89%E5%90%84%E8%A1%8C%E4%B8%9A%E5%8F%91%E7%A5%A8.04DRw
[WARNING][2023-07-05 21:27:38][search_google.py:92] - 链接内容低于200个字符：https://helpguide.sony.net/ilc/1710/v1/zh-cn/search/search.html?search=%E7%9C%9F%E7%9A%84%E5%82%AC%E6%83%85%E9%A6%99%E6%B0%B4%E5%92%B8%E9%B1%BC%E8%B4%AD%E4%B9%B0(%E8%B4%AD%E4%B9%B0%E5%B9%B3%E5%8F%B0miyao85.com)%E5%BC%BA%E6%95%88%E5%8F%91%E6%83%85%E8%8D%AF%E7%BD%91%E4%B8%8A%E8%AE%A2%E8%B4%AD%E6%AD%A3%E5%93%81%E8%BF%B7%E5%A5%B8%E8%8D%AF%E7%BD%91%E4%B8%8A%E8%B4%AD%E4%B9%B0yk8nw1(%E8%B4%AD%E4%B9%B0%E5%B9%B3%E5%8F%B0miyao85.com)4re
[WARNING][2023-07-05 21:27:38][search_google.py:92] - 链接内容低于200个字符：https://zh.flightaware.com/live/flight/CES2533
[WARNING][2023-07-05 21:27:38][search_google.py:92] - 链接内容低于200个字符：https://www.mizunousa.com/search-results?w=%E6%AD%A6%E6%B1%89%E5%BC%80%E9%85%92%E5%BA%97%E5%8F%91%E7%A5%A8-%E6%AD%A6%E6%B1%89%E5%BC%80%E9%85%92%E5%BA%97%E5%8F%91%E7%A5%A8%E2%94%83%E5%BE%AE%E3%81%AE%E4%BF%A1:%20hnx618618%E2%94%83%E4%BF%9D%E7%9C%9F%20(Jh04)%E5%BC%80%E4%BD%8F%E5%AE%BF%E5%8F%91%E7%A5%A8%EF%B9%A8%E5%BC%80%E9%A4%90%E8%B4%B9%E5%8F%91%E7%A5%A8%EF%B9%A8%E5%BC%80%E9%85%92%E5%BA%97%E5%8F%91%E7%A5%A8%EF%B9%A8%E5%BC%80%E4%BC%9A%E8%AE%AE%E8%B4%B9%E5%8F%91%E7%A5%A8%EF%B9%A8%E5%BC%80%E5%92%A8%E8%AF%A2%E8%B4%B9%E5%8F%91%E7%A5%A8%EF%B9%A8%E5%BC%80%E6%88%BF%E7%A7%9F%E5%8F%91%E7%A5%A8%EF%B9%A8%E5%BC%80%E5%B9%BF%E5%91%8A%E8%B4%B9%E5%8F%91%E7%A5%A8(Jh04)
[WARNING][2023-07-05 21:27:39][search_google.py:92] - 链接内容低于200个字符：https://helpguide.sony.net/ilc/1710/v1/zh-cn/search/search.html?search=%E7%9C%9F%E7%9A%84%E4%BC%9F%E5%93%A5%E7%BD%91%E8%B4%AD(%E8%B4%AD%E4%B9%B0%E5%B9%B3%E5%8F%B0miyao85.com)%E6%AD%A3%E5%93%81%E9%BA%BB%E9%86%89%E6%B0%B4%E8%AE%A2%E8%B4%AD%E5%93%AA%E9%87%8C%E8%83%BD%E4%B9%B0%E5%88%B0%E6%AD%A3%E5%93%81%E5%A4%B1%E5%BF%86%E6%B0%B43ubm4p(%E8%B4%AD%E4%B9%B0%E5%B9%B3%E5%8F%B0miyao85.com)l7o

**Comment by cheungchazz** [comment]
这是geturl的问题，没有做解析，默认读不到就跳过了，等后续替代方案
